### ISSUE TITLE
请问下这个是否能够开源呢

### ISSUE THREAD

**Issue by qiaolin-li** [loggerhead/json4u-issue#1]
我看这个json对比的工具很清晰
请问下这个是否能够开源，或者弄成工具包呢？
我想加入到我写的这个工具里面来做多次响应结果的对比。
<img width="1200" alt="image" src="https://user-images.githubusercontent.com/32925394/232423894-2c76a043-234d-471a-b556-6facc46c648e.png">

**Comment by loggerhead** [comment]
现在代码耦合太重了，打算重构一版再考虑开源

**Comment by qiaolin-li** [comment]
好的，期待大佬开源
