### ISSUE TITLE
时间字符串格式化有误

### ISSUE THREAD

**Issue by lyf9580** [loggerhead/json4u-issue#2]
在格式化时，会在原先正常的时间字符串中加入空格，改变原先正常的时间字符串
如：
1、"2022-12-01T17:47:21.207"，变成"2022-12-01T17: 47: 21.207"
2、"2023-05-12 15:04:53"，变成"2023-05-1215: 04: 53"

希望能尽快修复，这个网站给予我非常大的帮助，十分感谢！

**Comment by lyf9580** [comment]
似乎关闭“粘贴时自动格式化”功能可以暂时解决这个问题^_^

**Comment by loggerhead** [comment]
@MIMO-SO 已经修复了哈，可以清一下缓存，使用 2.0.0~
