### ISSUE TITLE
有考虑做成插件上架到一些常用的开发工具中吗

### ISSUE THREAD

**Issue by 00LT00** [loggerhead/json4u-issue#3]
如题，比如说raycast、utools、Alfred等
json4u是我目前用过最nb的json处理工具，但是大部分情况下我还是用utools自带的json解析器用的多
最主要就是方便，不需要打开浏览器直接粘贴进去就能用，只有是utools干不了的活我才能想起来这个，所以大佬考虑把这个拓展出去吗

**Comment by loggerhead** [comment]
如果作为一个 iframe 嵌入，体验上能接受么？我在 3.0 调研、评估一下

**Comment by loggerhead** [comment]
@00LT00 可以提供一下你的使用场景的截图么？想了解一下都是通过插件使用哪些功能

**Comment by shuaiyy** [comment]
> @00LT00 可以提供一下你的使用场景的截图么？想了解一下都是通过插件使用哪些功能

it-tools 这个工具箱是用docker部署的web服务，有些内网环境无法连接外网使用json4u，也没法登录服务器使用cmd工具jq，我是在内网部署了一个it-tools服务， https://github.com/CorentinTh/it-tools ，json4u比it-tools里的json工具更易用、强大；

**Comment by loggerhead** [comment]
@shuaiyy 近期会开源，到时候可以看看能不能自行部署到内网。插件后面我想了一下，难点在于需要覆盖的 app 多，且**无法保证体验一致**，所以暂不打算支持插件了
