### ISSUE TITLE
建议做个临时的分享功能

### ISSUE THREAD

**Issue by shuaiyy** [loggerhead/json4u-issue#4]
1. 比如打开 https://json4u.com?share_key=xxx-ooo-yyyy, 可以还原分享者的某次内容快照
2. 这样也能增加站点的传播

**Comment by loggerhead** [comment]
@shuaiyy 目前是支持的，比如 https://json4u.com?share=13w4m
![image](https://github.com/user-attachments/assets/fba40894-f27f-48b9-a42f-bef5f27eb342)
